### ISSUE TITLE
GUI: Support the Chrome Trace Format

### ISSUE THREAD

**Issue by besnardjb** [async-mpi-benchmarks/interpol#4]
# Outputing Traces

You have a simple trace format but there are simple tools to support extended views.

- Chrome Trace format : https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview
- Perfetto viewer: https://perfetto.dev/

Here you may project some scalar informations too in combination with per-process behavior, particularly outlining non-blocking windows.

**Comment by besnardjb** [comment]
This is probably more on the interface side.

**Comment by dssgabriel** [comment]
Closing the issue here and re-opening it in the `Interface` repo.
